server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: demo
  profiles:
    active: dev
  graphql:
    http:
      path: /biblio
    graphiql:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:bibliotheque}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
